name: Android Build CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release/*'
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_spotless:
    name: Check spotless
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Check formatting using spotless
        run: ./gradlew spotlessCheck --stacktrace

  build:
    name: Build debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          ./gradlew assembledebug --stacktrace
        env:
          TZ: UTC
      - name: Publish on Telegram (now on DM for testing)
        run: |
          cp app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk app/build/outputs/apk/fdroid/debug/amaze-fdroid-debug-${GITHUB_REF##*/}-${{ github.sha }}.apk
          cp app/build/outputs/apk/play/debug/app-play-debug.apk app/build/outputs/apk/play/debug/amaze-play-debug-${GITHUB_REF##*/}-${{ github.sha }}.apk
          echo $(curl -v -F "chat_id=1418165684" -F document=@app/build/outputs/apk/fdroid/debug/amaze-fdroid-debug-${GITHUB_REF##*/}-${{ github.sha }}.apk https://api.telegram.org/${{ secrets.AMAZE_BOT_ID }}:${{ secrets.TELEGRAM_INTEGRATION_KEY }}/sendDocument && curl -v -F "chat_id=1418165684" -F document=@app/build/outputs/apk/play/debug/amaze-play-debug-${GITHUB_REF##*/}-${{ github.sha }}.apk https://api.telegram.org/${{ secrets.AMAZE_BOT_ID }}:${{ secrets.TELEGRAM_INTEGRATION_KEY }}/sendDocument)