name: Android Build CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release/*'
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_spotless:
    name: Check spotless
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Check formatting using spotless
        run: ./gradlew spotlessCheck --stacktrace

  build:
    name: Build debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          ./gradlew assembledebug --stacktrace
        env:
          TZ: UTC

  publish:
    name: Publish on Telegram
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Parse variables
        id: parse-vars
        run: |
          echo '::set-output name=COMMIT_COUNT::git rev-list --count HEAD'
          echo '::set-output name=VERSION_NAME::${GITHUB_REF##*/} | sed 's/release\///''
      - name: Publish on Telegram
        run: |
          cp app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk app/build/outputs/apk/fdroid/debug/amaze-fdroid-${steps.parse-vars.outputs.VERSION_NAME}-${{steps.parse-vars.outputs.COMMIT_COUNT}}.apk
          cp app/build/outputs/apk/play/debug/app-play-debug.apk app/build/outputs/apk/play/debug/amaze-play-${steps.parse-vars.outputs.VERSION_NAME}-${{steps.parse-vars.outputs.COMMIT_COUNT}}.apk
          echo $(curl -v -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" -F document=@app/build/outputs/apk/fdroid/debug/amaze-fdroid-${steps.parse-vars.outputs.VERSION_NAME}-${{steps.parse-vars.outputs.COMMIT_COUNT}}.apk https://api.telegram.org/${{ secrets.AMAZE_BOT_ID }}:${{ secrets.TELEGRAM_INTEGRATION_KEY }}/sendDocument && curl -v -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" -F document=@app/build/outputs/apk/play/debug/amaze-play-${steps.parse-vars.outputs.VERSION_NAME}-${{steps.parse-vars.outputs.COMMIT_COUNT}}.apk https://api.telegram.org/${{ secrets.AMAZE_BOT_ID }}:${{ secrets.TELEGRAM_INTEGRATION_KEY }}/sendDocument)